---
- name: "Store LB DNS to local"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  pre_tasks:
    - name: "Install 'unzip'"
      apt:
        name: [ "unzip" ]
        state: latest
        update_cache: yes
  roles:
    # - awscli
    - kubernetes
  tasks:
    - name: LB DNS
      shell: "./bin/kubectl get svc --all"
      # shell: "./bin/kubectl get svc {{ ENVIRONMENT_NAME }}-service"
      register: elb_dns
      changed_when: false
      args:
        chdir: $HOME

    - name: Print to local file
      copy:
        content: "{{ elb_dns.stdout }}"
        dest: "~/elb_dns.txt"
      delegate_to: localhost
